config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :account_activations, only: [:edit]

  resources :attempts
  resource :session, only: [:new, :create, :destroy]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :drill_groups do

    get '/questions/start', to: 'questions#start_group', as: :questions_start
    get '/questions/finish', to: 'questions#finish_group', as: :questions_finish
    post '/questions/:id/answer', to: 'questions#answer', as: :question_answer
    get '/questions/:id/next', to: 'questions#next', as: :question_next

    resources :questions do
      resources :solutions
    end
  end

  get('/', { to: 'home#index', as: :root })
  get('/sign_up/thanks', { to: 'users#thanks' })

 # get('/forgot_password', {to: 'password_resets#forgot_password'})
  get('/users/:id/drill_group_tabs', {to: 'users#drill_group_tabs', as: :drill_group_tabs})
  post('/attempts/:drill_id/add_to_drills', {to: 'attempts#add_to_drills', as: :add_to_drills})
  get('/forgot_password', {to: 'users#forgot_password'})
  get('/leaderboard', {to: 'leaderboard#index'})

end

app/models/drill_group.rb
class DrillGroup < ApplicationRecord

  belongs_to :user

  has_many :questions, dependent: :destroy
  has_many :attempts, dependent: :destroy
  has_many :user_attempts, through: :attempts, source: :user

  def available_levels
    [['beginner', 'Beginner'], ['intermediate', 'Intermediate'], ['advanced', 'Advanced']]
  end

  validates :name, :description, :points, presence: true

  validate :valid_level

  private

  def valid_level
    valids = available_levels.map { |lvl| lvl.first }
    unless valids.include? level
      errors.add :level, "invalid"
    end
  end
end

app/controllers/drill_groups_controller.rb
class DrillGroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_drill_group, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user!, only: [:destroy, :edit, :update]
  # before_action :authorize_user!, except: [:show]

  def index
    @user = current_user
    @drill_groups = @user.drill_groups
  end

  def show
    @question = Question.new
  end

  def new
    @drill_group = DrillGroup.new
  end

  def create
    @drill_group = DrillGroup.new drill_group_params
    @drill_group.user = current_user

    if @drill_group.user.is_admin?
      if @drill_group.save
        redirect_to drill_group_path(@drill_group)
      else
        flash.now[:alert] = @drill_group.errors.full_messages.join(', ')
        render :new
      end
    else
      flash[:alert] = 'Must be admin'
      redirect_to drill_group_tabs_path(current_user)
    end

    # TODO: test create question form (creat a questions controller)
  end

  def edit
  end

  def update
    if @drill_group.update drill_group_params
      redirect_to drill_group_path(@drill_group)
    else
      flash.now[:alert] = @drill_group.errors.full_messages.join(', ')
      render :edit
    end
  end

  def destroy
    if @drill_group.destroy
      redirect_to drill_groups_path
    else
      flash.now[:alert] = 'Cannot delete'
      render :index
    end
  end

  private
  def find_drill_group
    @drill_group = DrillGroup.find params.require(:id)
  end

  def drill_group_params
    params.require(:drill_group).permit(:name, :description, :level, :points)
  end

  def authorize_user!
    unless can?(:crud, @drill_group)
      flash[:alert] = 'Access Denied!'
      redirect_to drill_groups_path
    end
  end
end

app/views/drill_groups/_form.html.erb
  <%= simple_form_for @drill_group do |f| %>

  <div class="row my-3">
    <div class="col-2">
      <%= f.label :name %>
    </div>
    <div class="col-5 offset-1">
      <%= f.input_field :name, class: 'w-100' %>
    </div>
  </div>

  <div class="row">
    <div class="col-2">
      <%= f.label :description %>
    </div>
    <div class="col-5 offset-1">
      <%= f.text_area :description, rows: '5', class: 'w-100' %>
    </div>
  </div>

  <div class="row">
    <div class="col-2">
      <%= f.label :level %>
    </div>
    <div class="col-5 offset-1 radio">
      <%= f.collection_radio_buttons :level, @drill_group.available_levels, :first, :last, class: 'w-100' %>
    </div>
  </div>

  <div class="row">
    <div class="col-2">
      <%= f.label :points %>
    </div>
    <div class="col-5 offset-1">
      <%= f.input_field :points, class: 'w-100' %>
    </div>
  </div>

  <div class="row">
    <div class="col-2 offset-3">
      <%= f.submit 'Save', class: 'btn btn-secondary btn-lg mt-3' %>
    </div>
  </div>

  <% end %>

app/views/drill_groups/_solution_fields.html.erb
<div class='nested-fields'>
  <%= f.input :answer %>
  <%= f.input :input %>
  <%= f.input :output %>
  <%= link_to_remove_association 'Remove Solution', f, class: 'btn-small btn-outline-secondary' %>
</div>

app/views/drill_groups/edit.html.erb
<div class="container mt-3">
  <h3>Edit Drill Group</h3>
  <%= render 'form' %>
</div>

app/views/drill_groups/index.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-lg-9 col-md-8 col-sm-7">
      <h1>Drill Groups</h1>
    </div>

    <div class="col-lg-3 col-md-4 col-sm-5 mt-2">
      <%= link_to 'Add Group', new_drill_group_path, class: 'btn btn-secondary' %>
    </div>
  </div>
</div>

<div class="container drill-group-index">
  <% @drill_groups.each do |drill_group| %>
    <div class="card card-opacity mb-3" style="max-width: 60rem">
      <div class="card-body card-body-opacity">
        <div class="row">
          <div class="col-lg-9 col-md-8 col-sm-7" style="font-size:20px">
            <%= drill_group.name %>
          </div>

          <div class="col-lg-3 col-md-4 col-sm-5 btn-group">
            <%= link_to 'View', drill_group_path(drill_group.id), class: 'btn btn-primary' %>
            <%= link_to 'Edit', edit_drill_group_path(drill_group), class: 'btn btn-outline-secondary' %>
            <%= link_to 'Delete', drill_group_path(drill_group), method: :delete, class: 'btn btn-outline-secondary' %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/drill_groups/new.html.erb
<div class="container mt-3">
  <h3>Create Drill Group</h3>
  <%= render 'form' %>
</div>

app/views/drill_groups/show.html.erb
<div class="container">
  <div class="row mt-4">
    <div class="col-8">
      <h3>Drill Group: <strong><%= @drill_group.name %> </strong>  (<%= @drill_group.points %> pts)</h3>
    </div>
    <div class="col-4 d-flex justify-content-end">
      <% if can?(:crud, @drill_group) %>
        <%= link_to 'Edit Group', edit_drill_group_path(@drill_group), class: 'btn btn-outline-secondary' %>
      <% end %>
    </div>
  </div>

  <div class="row mt-4">
    <div class="col-12">
      <strong><p><%= @drill_group.description %></p></strong>
    </div>
  </div>
</div>

<div class="container">
    <% @drill_group.questions.each do |question| %>
    <div class="card card-opacity drill-question">
      <div class="card-body">
        <div class="row">
          <div class="col-10">
            <p>Drill: <%= question.description %></p>
          </div>

          <div class="btn-group col-2 d-flex justify-content-end">
            <% if can?(:crud, question) %>
              <%= link_to 'Edit', edit_drill_group_question_path(@drill_group, question), class: 'btn btn-outline-secondary' %>
              <%= link_to 'Delete', drill_group_question_path(@drill_group, question), method: :delete, class: 'btn btn-outline-secondary' %>
            <% end %>
          </div>
        </div>
      </div>
</div>
<% end %>
</div>


  <div class="container" >
    <div class="card card-opacity" style="border:none">
      <div class="card-body">
        <h5>Add New Drill</h5>
        <%= render 'questions/form' %>
      </div>
    </div>
  </div>