config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :account_activations, only: [:edit]

  resources :attempts
  resource :session, only: [:new, :create, :destroy]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :drill_groups do

    get '/questions/start', to: 'questions#start_group', as: :questions_start
    get '/questions/finish', to: 'questions#finish_group', as: :questions_finish
    post '/questions/:id/answer', to: 'questions#answer', as: :question_answer
    get '/questions/:id/next', to: 'questions#next', as: :question_next

    resources :questions do
      resources :solutions
    end
  end

  get('/', { to: 'home#index', as: :root })
  get('/sign_up/thanks', { to: 'users#thanks' })

 # get('/forgot_password', {to: 'password_resets#forgot_password'})
  get('/users/:id/drill_group_tabs', {to: 'users#drill_group_tabs', as: :drill_group_tabs})
  post('/attempts/:drill_id/add_to_drills', {to: 'attempts#add_to_drills', as: :add_to_drills})
  get('/forgot_password', {to: 'users#forgot_password'})
  get('/leaderboard', {to: 'leaderboard#index'})

end

app/controllers/leaderboard_controller.rb
class LeaderboardController < ApplicationController

  BOARD_MAX_USERS = 10

  def index

    top_users = User.find_by_sql("SELECT
        sq1.user_id,
        SUM(sq1.max_pts) AS total_pts
      FROM (
        SELECT
          att.user_id,
          MAX(att.score * dgp.points) AS max_pts
        FROM
          attempts att
          INNER JOIN drill_groups dgp ON att.drill_group_id = dgp.id
        GROUP BY
          att.user_id,
          att.drill_group_id
      ) sq1
      GROUP BY
        sq1.user_id
      ORDER BY
        total_pts DESC
      LIMIT
        #{BOARD_MAX_USERS}")

    @leaders = [];

    top_users.each do |usr|
      @leaders << {
        user: User.find(usr.user_id),
        points: usr.total_pts,
        badges: badges(usr.total_pts)
      }
    end

    if user_signed_in?

      curr = User.find_by_sql("SELECT
          sq1.user_id,
          SUM(sq1.max_pts) AS total_pts
        FROM (
          SELECT
            att.user_id,
            MAX(att.score * dgp.points) AS max_pts
          FROM
            attempts att
            INNER JOIN drill_groups dgp ON att.drill_group_id = dgp.id
          WHERE
            att.user_id = #{current_user.id}
          GROUP BY
            att.user_id,
            att.drill_group_id
        ) sq1
        GROUP BY
          sq1.user_id")

      @current_user_points = curr[0]&.total_pts
      @current_user_badges = badges(@current_user_points)
    end
  end

  private

  def badges(score)
    if score.nil?
      0
    else
      (score / 62.5).to_i
    end
  end
end

app/views/leaderboard/index.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-12">
      <div class="">
        <h1><strong>Leaders</strong></h1>
      </div>
      <% if !user_signed_in? %>
      <div class="d-flex justify-content-end">
        <%= link_to 'Sign In', new_session_path %>
        ✙
        <%= link_to "Sign Up", new_user_path %>
      </div>
      <% end  %>
    </div>
  </div>
  <div class="row">
    <div class="<%= (user_signed_in?) ? 'col-8' : 'col-12' %>">
      <% @leaders.each.with_index do |leader, index| %>
        <ul class="list-group">
          <li class="list-group-item list-group-item-primary d-flex justify-content-between">
            <strong><%= index + 1 %> ✦   <%= leader[:user].full_name %></strong>
            <span><strong><%= number_with_delimiter leader[:points].to_i %></strong> points / <strong><%= number_with_delimiter leader[:badges] %></strong> badges</span>
          </li>
        </ul>
        <br>
      <% end %>
    </div>
    <% if user_signed_in? %>
      <div  class="col-4 center-text">
        <div id="user-points" class="row justify-content-center">
          <br>
          <h1 style="margin-left:5px"><strong>YOU</strong></h1>
          <p style="margin-left:10px"><strong><%= number_with_delimiter @current_user_points.to_i %></strong> points <br>
          <strong><%= number_with_delimiter @current_user_badges %></strong> badges</p>
        </div>
      </div>
    <% end %>
  </div>
</div>