config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :account_activations, only: [:edit]

  resources :attempts
  resource :session, only: [:new, :create, :destroy]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :drill_groups do

    get '/questions/start', to: 'questions#start_group', as: :questions_start
    get '/questions/finish', to: 'questions#finish_group', as: :questions_finish
    post '/questions/:id/answer', to: 'questions#answer', as: :question_answer
    get '/questions/:id/next', to: 'questions#next', as: :question_next

    resources :questions do
      resources :solutions
    end
  end

  get('/', { to: 'home#index', as: :root })
  get('/sign_up/thanks', { to: 'users#thanks' })

 # get('/forgot_password', {to: 'password_resets#forgot_password'})
  get('/users/:id/drill_group_tabs', {to: 'users#drill_group_tabs', as: :drill_group_tabs})
  post('/attempts/:drill_id/add_to_drills', {to: 'attempts#add_to_drills', as: :add_to_drills})
  get('/forgot_password', {to: 'users#forgot_password'})
  get('/leaderboard', {to: 'leaderboard#index'})

end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save :downcase_email
  before_create :create_activation_digest
  has_secure_password
  has_many :drill_groups, dependent: :destroy
  has_many :attempts, dependent: :destroy
  has_many :drill_group_attempts, through: :attempts, source: :drill_group
  has_many :current_questions, class_name: "Question", through: :attempts

  validates :first_name, :last_name, presence: true

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  validates :email,
    presence: true,
    uniqueness: true,
    format: VALID_EMAIL_REGEX

  def full_name
    "#{first_name} #{last_name}".strip
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # Sets the password reset attributes
  def create_reset_digest
    self.reset_token = User.new_token
    self.save
  end

  # Sends password reset email
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  # Returns true if a password reset has expired



  private

  #Converts emails to all lower-case
  def downcase_email
    self.email = email.downcase
  end

  #Creates and assigns the activation token and digest
  def create_activation_digest
    self.activation_token = User.new_token
    self.activation_digest = User.digest(self.activation_token)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def index
  end

  def create
    @user = User.new user_params
    if @user.save
      UserMailer.account_activation(@user).deliver_now
      redirect_to sign_up_thanks_path
    else
      flash.now[:alert] = @user.errors.full_messages.join(', ')
      render :new
    end
  end

  def show
    @user = User.find params[:id]
    @attempts = @user.attempts.order(drill_group_id: :asc)
  end

  def update
    @user = User.find params[:id]

    if @user.update user_params
      flash[:notice] = 'Successfully updated!'
      redirect_to drill_group_tabs_path(@user)
    else
      flash[:alert] = 'Cannot update information'
      redirect_to user_path(@user)
    end
  end

  def drill_group_tabs
    @user = current_user
    @all_drill_groups = DrillGroup.all
    @my_drill_groups = @user&.drill_group_attempts&.uniq
    
  end


  def forgot_password

  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

end

app/views/users/drill_group_tabs.html.erb
<div class="drill_group_tabs">

  <ul class="nav nav-tabs" role="tablist">
    <li class="nav-item">
      <a class="nav-link active" data-toggle="tab" href="#mydrills" role="tab" style="font-weight: bold;">My Drillz</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="tab" href="#alldrills" role="tab" style="font-weight: bold;">All Drillz</a>
    </li>
  </ul>

  <div class="tab-content">

    <div class="tab-pane show active" id="mydrills" role="tabpanel">
      <div id="my_drill_groups" class="tab-pane tabs-container transitions-enabled infinite-scroll clearfix masonry">
        <%if @my_drill_groups.length > 0 %>
        <% @my_drill_groups.each do |drill|  %>
        <div class="m-2 box">
          <div class="card" style="width: 18rem;">
            <div class="card-body">
              <h5 class="card-title"><%= drill.name %></h5>
              <h6 class="card-subtitle mb-2 text-muted">Taken: <%= drill.attempts.where(user: current_user).maximum("score") == nil ? 0 : drill.attempts.where(user: current_user).count %> Times</h6>
              <p class="card-text">Score: <%= drill.attempts.where(user: current_user).maximum("score") == nil ? "N/A" : number_to_percentage((drill.attempts.where(user: current_user).maximum("score")*100), precision: 0) %> </p>
              <%= link_to "Start", drill_group_questions_start_path(drill), class: "card-link", style: "font-weight: bold; font-size: 13px;" %>
              <%= link_to "Delete", attempt_path(drill.attempts.find_by user: current_user), method: :delete, class: "card-link", style: "font-weight: bold; font-size: 13px;" %>
            </div>
          </div>
        </div>
        <% end  %>
        <% else %>
        <div class="no-drill-groups">
          <h1 class="get-drilling">Get Drillin'!</h1>
        </div>
        <% end %>
      </div>
    </div>

    <div class="tab-pane" id="alldrills" role="tabpanel">
      <div id="all_drill_groups" class="tab-pane tabs-container transitions-enabled infinite-scroll clearfix masonry">
        <% @all_drill_groups.each do |drill|  %>
        <div class="box panel panel-default">
          <div class="card" style="width: 18rem;">
            <div class="card-body">
              <h5 class="card-title"><%= drill.name %></h5>
              <h6 class="card-subtitle mb-2 text-muted"><%= drill.level %> • <%= drill.points %> pts</h6>
              <p class="card-text"><%= drill.description %></p>
              <%= button_to "Add To My Drills", add_to_drills_path(drill), method: :post, class: "card-link btn btn-outline-primary btn-sm" %>
            </div>
          </div>
        </div>
        <% end  %>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
$('.nav-link').on('click', function() {
  $('#my_drill_groups, #all_drill_groups').masonry({
    isAnimated: !Modernizr.csstransitions
  });
});

(function () {

  const tablistClick = function (evt) {

    const { target } = evt;

    if (!target.matches("a.nav-link[role='tab']:not(.active)")) {
      return;
    }

    setTimeout(function () {
      target.click();
    }, 50);
  };

  document.querySelector("ul.nav.nav-tabs[role='tablist']").addEventListener("click", tablistClick);
}());
</script>

app/views/users/forgot_password.html.erb
<div class="container">
  <div>
    <h2 class="label">Reset Your Password</h2>
    <h3 class="label">To reset your password, please insert your email</h3>
  </div>

  <%= form_for  do |f| %>
  <div>
    <div class="form-group label">
      <div class="form">
        <%= f.email_field :email, class: 'form-control input forgot_password_form' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.submit "Reset Your Password", class: " btn-lg submit"%>
    </div>
  </div>
<% end %>
</div>

app/views/users/new.html.erb
<div class="container">
  <h2 class="label">Become a Ninja!</h2>

  <%= form_for @user do |f| %>

    <div class="form-group label">
      <%= f.text_field :first_name, class: 'form-control sign_up_form', placeholder: 'First Name' %>
    </div>

    <div class="form-group label">
      <%= f.text_field :last_name, class: 'form-control sign_up_form', placeholder: 'Last Name' %>
    </div>

    <div class="form-group label">
      <%= f.email_field :email, class: 'form-control sign_up_form', placeholder: 'Email' %>
    </div>

    <div class="form-group label">
      <%= f.password_field :password, class: 'form-control sign_up_form', placeholder: 'Password' %>
    </div>

    <div class="form-group label">
      <%= f.password_field :password_confirmation, class: 'form-control sign_up_form', placeholder: 'Confirm Password' %>
    </div>

    <div class="form-input justify-content-center">
      <%= f.submit "Sign Up", class: "btn btn-outline-secondary submit", placeholder: 'Submit' %>
    </div>

    <div class="d-flex justify-content-center">
      <%= link_to 'Already a Ninja?', new_session_path, class: 'have-account-text' %>
    </div>

  <% end %>
</div>

app/views/users/show.html.erb
<div class="container">
  <h1><%= @user.full_name %></h1>

  <div id="accordion" class="mt-3">
    <div class="card card-opacity">
      <div class="card-header" id="#view-scores">
        <h5 class="mb-0 text-center">
          <button class="btn btn-link" data-toggle="collapse" data-target="#view-scores" aria-expanded="true" aria-controls="view-scores">
            <h6 class="profile-headers">View Scores</h6>
          </button>
        </h5>
      </div>

      <div id="view-scores" class="collapse" aria-labelledby="view-scores" data-parent="#accordion">
        <div class="card-body">
            <table class="table">
              <thead class="thead-light">
                <tr>
                  <th scope="col">Drill Group</th>
                  <th scope="col">Score</th>
                </tr>
              </thead>

              <% @attempts.each do |attempt| %>
              <% drill_group = DrillGroup.find (attempt.drill_group_id) %>
              <tbody>
                <tr>
                  <% if attempt.score %>
                    <td><%= drill_group.name %></td>
                    <td><%= number_to_percentage((attempt.score*100), precision: 0) %></td>
                  <% end %>
                </tr>
              </tbody>
              <% end %>
            </table>
        </div>
      </div>
    </div>

    <div class="card card-opacity mt-3">
      <div class="card-header" id="#edit-info">
        <h5 class="mb-0 text-center">
          <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#edit-info" aria-expanded="false" aria-controls="edit-info">
            <h6 class="profile-headers">Edit Information</h6>
          </button>
        </h5>
      </div>
      <div id="edit-info" class="collapse" aria-labelledby="edit-info" data-parent="#accordion">
        <div class="card-body">
          <%= simple_form_for @user do |f| %>
            <%= f.input :first_name, required: false %>
            <%= f.input :last_name, required: false %>
            <%= f.input :email, required: false %>

            <%= f.submit 'Update Information', method: 'PATCH', class: 'btn btn-secondary' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- id: 153,
user_id: 19,
drill_group_id: 45,
score: 183.0,
current_question_id: 227,
created_at: "2018-03-18 18:49:13",
updated_at: "2018-03-18 18:49:13" -->

app/views/users/thanks.html.erb
<br />
<div class="d-flex justify-content-center">
  <h2>Thank you for registering! You will be notified when your account is approved</h2>
</div>