config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :account_activations, only: [:edit]

  resources :attempts
  resource :session, only: [:new, :create, :destroy]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :drill_groups do

    get '/questions/start', to: 'questions#start_group', as: :questions_start
    get '/questions/finish', to: 'questions#finish_group', as: :questions_finish
    post '/questions/:id/answer', to: 'questions#answer', as: :question_answer
    get '/questions/:id/next', to: 'questions#next', as: :question_next

    resources :questions do
      resources :solutions
    end
  end

  get('/', { to: 'home#index', as: :root })
  get('/sign_up/thanks', { to: 'users#thanks' })

 # get('/forgot_password', {to: 'password_resets#forgot_password'})
  get('/users/:id/drill_group_tabs', {to: 'users#drill_group_tabs', as: :drill_group_tabs})
  post('/attempts/:drill_id/add_to_drills', {to: 'attempts#add_to_drills', as: :add_to_drills})
  get('/forgot_password', {to: 'users#forgot_password'})
  get('/leaderboard', {to: 'leaderboard#index'})

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Drill Ninjaz</title>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag asset_path('favicon.ico'), :rel => 'icon', :type => "image/x-icon" %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if !@hide_navbar %>
    <nav class="navbar navbar-light ">

      <div  class="col-1" id="navbar-logo" style="height: 100px;">
        <%= image_tag( "ninja.png", style: "height: 75px; ") %>
        <div id="ninja-nav"><strong> Drill Ninjaz</strong></div>
      </div>


      <div class="col text", style="font-size: 20px">
        <% if current_user.present? %>
        <%= link_to 'Drillz', drill_group_tabs_path(current_user) %>
        |
        <% end %>

        <%= link_to 'Leaderboard', leaderboard_path %>

        <% if current_user&.is_admin? %>
        |
        <%= link_to 'My Drillz', drill_groups_path %>
        <% end %>
      </div>

      <% if user_signed_in? %>
      <div class="col text" style="text-align: right; font-size: 20px">
        <span>Hello
          <%= current_user.first_name %>,</span>

          <%= link_to 'Profile', user_path(current_user) %>
          |
          <%= link_to 'Logout', session_path, method: :delete %>
        </div>
        <% end %>
      </nav>
    <% end %>


    <div class="container-fluid">
      <% if flash[:notice].present? %>
        <div class="alert alert-primary alert-dismissible fade show d-flex justify-content-center" role="alert">
          <%= flash[:notice] %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <% elsif flash[:alert].present? %>
          <div class="alert alert-danger alert-dismissible fade show d-flex justify-content-center" role="alert">
            <%= flash[:alert] %>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        <% end %>

        <%= yield %>
      </body>
    </html>